### ISSUE TITLE
Link to Collection Explorer

### ISSUE THREAD

**Issue by f27wood** [Conal-Tuohy/NMA-API#12]
From developer:

There is no direct link between an object in the /object endpoint and collection
explorer, so I need to simply build this manually
( http://collectionsearch.nma.gov.au/object/{$data- >id} )

Answer:

A link to the source on Collection Explorer will be included in the MVP, as will a link to the full text which may be a different link.

**Comment by srowlands** [comment]
👍 
I can see the link back via `_meta->hasFormat` link in simple format, nothing yet in json-ld

**Comment by Conal-Tuohy** [comment]
In the JSON-LD version the web page is considered another resource about the object, in the same way as the description is. So you'll find it under "subject_of". It is the resource which is classified as a web page. The classification has the id http://vocab.getty.edu/aat/300264578 (which if you follow it, you'll see means "web pages"). It should also have a label "web page", but it doesn't.

**Comment by staplegun** [comment]
In the MVP release the link appears in both the simple format and JSON-LD (as noted above).
