### ISSUE TITLE
Upper limit on limit parameter

### ISSUE THREAD

**Issue by f27wood** [Conal-Tuohy/NMA-API#14]
From tester:

I had assumed I would need to use pagination to retrieve large data-sets (as per the
pagination section of the docs
https://github.com/Conal-Tuohy/NMA-API/wiki/Getting-started )
This works, however there does not yet appear to be an upper limit on the ‘limit’ parameter. This may be expected at this point during development, but thought it was worth raising.

**Comment by Conal-Tuohy** [comment]
Added a maximum `limit` of 100 and minimum of 1, and a default (if not specified in the query at all) of 50. See revision 26f9bae2ee9a073ec4c7d2cfd11f0ad13165cca6

I will close this ticket now but feel free to reopen it if these values aren't appropriate.
