### ISSUE TITLE
Linked art included_in type field

### ISSUE THREAD

**Issue by f27wood** [Conal-Tuohy/NMA-API#17]
In the linked art JSON format, the included_in has a type value of PhysicalObject. However, this is a collection, so should the type be 'Collection' or something similar to indicate it is a collection?

Example code:

    "included_in" : 
    { "type" : "PhysicalObject",
      "value" : "American-Australian Scientific Expedition to Arnhem Land (AASEAL) collection",
      "classified_as" : 
      { "id" : "http:\/\/vocab.getty.edu\/aat\/300025976",
        "type" : "Type",
        "label" : "collection (object grouping)" } } }

**Comment by Conal-Tuohy** [comment]
I agree: the resource's type should be "Collection", representing the CIDOC CRM class `E78_Collection`.

We can use this class now by linking to "Linked Art's' [cidoc-extension.json](https://github.com/linked-art/linked.art/blob/master/content/ns/v1/cidoc-extension.json) JSON-LD context.

**Comment by f27wood** [comment]
Seems good to me

**Comment by Conal-Tuohy** [comment]
Collections are now represented using the E78_Collection class. e.g. http://nma.conaltuohy.com/object/165539#
