### ISSUE TITLE
Searching on "type" no longer includes AdditionalType field

### ISSUE THREAD

**Issue by srowlands** [Conal-Tuohy/NMA-API#28]
One of the testing tasks requires the following 
> ...displays all objects with the type of "toy trains”

During beta testing this was possible with the following query:
  http://nma.conaltuohy.com/object?type=toy+train&media=*&format=simple

Now this produces a 404. My current theory is the `additionalType` field is no longer included in the type query. You can get a similar result set by instead searching on ?text=toy+train+set.

**Comment by Conal-Tuohy** [comment]
Your theory is correct. In the early beta the search index's `type` field included both the primary types (`object`, `party`, etc) and also the detailed classifications (toy trains, magazines, kitchen sinks). the good news is that in the current API we now have `additionalType` as a URL parameter, corresponding to ``additionalType and `classified_as` in the simple JSON and JSON-LD formats, respectively. 

The good news

**Comment by srowlands** [comment]
Perfect! Thanks, closing this one.
