### ISSUE TITLE
Unable to search for irn (id)

### ISSUE THREAD

**Issue by f27wood** [Conal-Tuohy/NMA-API#62]
We often use the IRN to search for an object. This doesn't seem possible in the API?

We can search on the identifier which is the accession number, but not the 'id' which is the irn.

I think we would want to search by irn as well. Can be included in v2.0, or let me know if out of scope for this part of the project, and we can include later.

**Comment by Conal-Tuohy** [comment]
To search for object by IRN you just append the IRN to the base URI `object/` e.g. for IRN 56167 you have https://csapi-test.nma.gov.au/object/56167

**Comment by f27wood** [comment]
Ahh to easy! Closing this one.
